version: '3'
services:
  data_collector:
    build: .
    image: data_collector:latest
    restart: always
    volumes:
      - ./app:/app
    depends_on:
      - clickhouse
    command: python3 -u ./data_collector.py

  data_quality_check:
    build: .
    image: data_quality_check:latest
    restart: always
    volumes:
      - ./app:/app
    depends_on:
      - clickhouse
    command: python3 -u ./data_quality_check.py

  load_history:
    build: .
    image: load_history:latest
    #restart: always
    volumes:
      - ./app:/app
    depends_on:
      - clickhouse
    command: python3 -u ./load_history.py

  clickhouse:
    image: yandex/clickhouse-server
    restart: always
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    volumes:
      - ./data:/var/lib/clickhouse